### ISSUE TITLE
100% Reproducible segfault on http://www.511.org

### ISSUE THREAD

**Issue by patelbhavesh** [jech/polipo#47]
Goto the website http://www.511.org
Observe a segmentation fault.I am on debian wheezy
~/develop/polipo/polipo$ sudo gdb --args ./polipo -c /etc/polipo/config
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /media/videos/develop/polipo/polipo/polipo...done.
(gdb) run
Starting program: /media/videos/develop/polipo/polipo/polipo -c /etc/polipo/config

Program received signal SIGSEGV, Segmentation fault.
httpServerReplyHandler (status=-65540, event=0x63a460, srequest=0x63a480) at server.c:1793
1793	    assert(request->object->flags & OBJECT_INPROGRESS);
(gdb) bt
#0  httpServerReplyHandler (status=-65540, event=0x63a460, srequest=0x63a480) at server.c:1793
#1  0x0000000000404f1c in do_scheduled_stream (status=<optimized out>, event=0x63a460) at io.c:282
#2  0x00000000004044e5 in pokeFdEventHandler (tevent=<optimized out>) at event.c:569
#3  0x0000000000404561 in runTimeEventQueue () at event.c:492
#4  0x0000000000404725 in eventLoop () at event.c:654
#5  0x0000000000402aa1 in main (argc=3, argv=<optimized out>) at main.c:165

**Comment by patelbhavesh** [comment]
I no longer able to reproduce this crash.I think it might be because newer versions of firefox disables flash plugin by default and maybe that is causing this crash to go away.not sure though
